source 'https://rubygems.org'

ruby '3.2.0'

# Web framework
gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0'

# Database
gem 'sqlite3', '~> 1.6'
gem 'activerecord', '~> 7.0'
gem 'sinatra-activerecord', '~> 2.0'

# JSON handling
gem 'json', '~> 2.6'

# Environment management
gem 'dotenv', '~> 2.8'

# CORS support
gem 'rack-cors', '~> 2.0'

# Development gems
group :development do
  gem 'pry', '~> 0.14'
  gem 'rerun', '~> 0.14'
end

group :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.0'
end
